### ISSUE TITLE
请问如何配置外部依赖？

### ISSUE THREAD

**Issue by yibie** [ginqi7/websocket-bridge#4]
emacs-websocket 加载不成功。
我的配置：

```
(use-package emacs-websocket :ensure nil
  :load-path "~/.emacs.d/lisp/emacs-websocket")
```

我的环境：
macOS 15.0
MacBook Pro M1Pro
emacs 30.0.91

**Comment by ginqi7** [comment]
emacs-websocket 的包名是：websocket ：

https://github.com/ahyatt/emacs-websocket/blob/40c208eaab99999d7c1e4bea883648da24c03be3/websocket.el#L1054

```
(use-package websocket :ensure nil
  :load-path "~/.emacs.d/lisp/emacs-websocket")
```

这样试试。

**Comment by yibie** [comment]
好的，已经没问题了
